[package]
name = "LEA_XMLWRITE_AD_TRY_C"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xml-rs = "0.8.4"
csv = "1.1.7"
serde = { version = "1.0.130", features = ["derive"] }


